src/AppBundle/Form/NewsAddType.php
<?php
/**
 * Created by PhpStorm.
 * User: Danil
 * Date: 24.05.2015
 * Time: 14:19
 */

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class NewsAddType extends AbstractType{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder->add('title', 'text');
        $builder->add('text', 'textarea');
        $builder->add('add', 'submit');
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\News',
        ));
    }

    public function getName()
    {
        return 'NewsAdd';
    }
}

src/AppBundle/Controller/AdministrationController.php
<?php
/**
 * Created by PhpStorm.
 * User: Danil
 * Date: 24.05.2015
 * Time: 1:56
 */

namespace AppBundle\Controller;


use AppBundle\Entity\News;
use AppBundle\Entity\Vacancy;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use AppBundle\Form\NewsAddType;
use AppBundle\Form\VacancyAddType;
use Symfony\Component\HttpFoundation\Request;


class AdministrationController extends Controller{

    public function indexAction()
    {
        $tickets = $this->getDoctrine()
            ->getRepository('AppBundle:ServiceOrder')
            ->findBy(array(), array('creation_date'=>'DESC'));

        return $this->render('AppBundle:administration:index.html.twig', array('tickets'=>$tickets));
    }
    public function usersIndexAction()
    {
        $users = $this->getDoctrine()
            ->getRepository('AppBundle:Account')
            ->findAll();
        return $this->render('AppBundle:administration/users:index.html.twig',
            array('users'=>$users));
    }
    public function newsIndexAction()
    {
        $news = $this->getDoctrine()
            ->getRepository('AppBundle:News')
            ->findAll();
        return $this->render('AppBundle:administration/news:index.html.twig',
            array('news'=>$news));
    }
    public function vacanciesIndexAction()
    {
        $vacancies = $this->getDoctrine()
            ->getRepository('AppBundle:Vacancy')
            ->findAll();
        return $this->render('AppBundle:administration/vacancies:index.html.twig',
            array('vacancies'=>$vacancies));
    }
    public function vacanciesAddAction()
    {
        $vacancy = new Vacancy();

        $form = $this->createForm(new VacancyAddType(), $vacancy, array(
            'action' => $this->generateUrl('administration_vacancies_add_form_check'),
        ));

        return $this->render(
            'AppBundle:administration:vacancies/add.html.twig',
            array('form' => $form->createView())
        );
    }
    public function vacanciesCreateAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $form = $this->createForm(new VacancyAddType(), new Vacancy());

        $form->handleRequest($request);
        if ($form->isValid()) {
            $vacancy = $form->getData();
            $vacancy->setAccount($this->getUser());
            $em->persist($vacancy);
            $em->flush();

            $this->redirect($this->generateUrl('administration_vacancies_index'));
        }
        return $this->render(
            'AppBundle:administration:vacancies/add.html.twig',
            array('form' => $form->createView())
        );
    }
    public function newsAddAction()
    {
        $news = new News();

        $form = $this->createForm(new NewsAddType(), $news, array(
            'action' => $this->generateUrl('administration_news_add_form_check'),
        ));

        return $this->render(
            'AppBundle:administration:news/add.html.twig',
            array('form' => $form->createView())
        );
    }
    public function newsCreateAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(new NewsAddType(), new News());

        $form->handleRequest($request);
        if ($form->isValid()) {
            $news_item = $form->getData();
            $news_item->setAccount($this->getUser());
            $em->persist($news_item);
            $em->flush();

            $this->redirect($this->generateUrl('administration_news_index'));
        }
        return $this->render(
            'AppBundle:administration:news/add.html.twig',
            array('form' => $form->createView())
        );
    }
}

src/AppBundle/Resources/views/administration/users/index.html.twig
{% extends 'base_admin.html.twig' %}

{% block content %}
    <style>
        td.middle
        {
            vertical-align: middle!important;
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function()
        {
            $('a').click(function(e)
            {
                var clicked_id = $(this).attr('id');
                var a_element = $(this);
                var element = $(this).find("i");
                if (element.is(".fa-lock"))
                {

                    var path = "{{ path( 'administration_users_unlock', { 'id': 'uid' }) }}";
                    path = path.replace('uid', clicked_id)
                    $.ajax(path).done(function() {
                        element.removeClass('fa-lock').addClass('fa-unlock');
                    });
                }
                else
                {
                    var path = "{{ path( 'administration_users_lock', { 'id': 'uid' }) }}";
                    path = path.replace('uid', clicked_id)
                    $.ajax(path).done(function() {
                        element.removeClass('fa-unlock').addClass('fa-lock');
                    });
                }
            });
        });
    </script>
    <h1 class="page-header">Список пользователей</h1>
    <table class="table table-striped table-hover ">
        <thead>
        <tr>
            <th>E-Mail</th>
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Отчество</th>
            <th>Цех</th>
            <th>Должность</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    {% if user.activationcode == null %}
                        <td class="middle success">{{ user.email }}</td>
                    {% else %}
                        <td class="middle warning">{{ user.email }}</td>
                    {% endif %}
                    <td class="middle">{{ user.lastname }}</td>
                    <td class="middle">{{ user.firstname }}</td>
                    <td class="middle">{{ user.middlename }}</td>
                    <td class="middle">{{ user.department.name }}</td>
                    <td class="middle">{{ user.position }}</td>
                    <td class="middle">
                        {% if user.blocked == true %}
                            <a id="{{ user.id }}" href="javascript:void(0);">
                                <i class="fa fa-lock"></i>
                            </a>
                        {% else %}
                            <a id="{{ user.id }}" href="javascript:void(0);">
                                <i class="fa fa-unlock"></i>
                            </a>
                        {% endif %}
                        <br />
                        <a><i class="fa fa-times"></i> </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}